# --------------------------------------[COMPASS RADAR]----------------------------------------------------
#                                     By xX_andrescol_Xx
#                                     Configuration Guide
# ---------------------------------------------------------------------------------------------------------
# trackerPlayer.disableInWorlds: put here the worlds where you want the compass doesn't tracker players
# trackerPlayer.enable: Do you want tracker players?
# trackerPlayer.maxDistance: It's the max distance on which compass is going to find players. Set 0 for all the world
# trackerPlayer.playerNameUntil: Distance up to which the player name is displayed
# trackerPlayer.  stopTrackingAt: Distance up to which the players are tracked
# trackerLocation: You can create specific location for what the compass points them
# trakcerLocation.enable: Do you want to enable this?
# trakcerLocation.maxDistance: Max distance o which compass is going to find locations. set 0 for all the world
# trackerLocation.locations: there are the all location that you will create with the specific location. Keep in mind
# that x, y and z are Integers
# hooks.factions.onlyNeutralEnemy: this section, only works if CompassRadar is hook with Factions. set to true if
# you want players enemy or neutrals will be tracked. Keep in mind that if you set false it, factions members will be tracked too
# [WARNING] I suggest you that the trackerPlayer.maxDistance is less than 50, because under 50 blocks if the two players
# have a compass, the compasses may go crazy

trackerPlayer:
  enable: true
  maxDistance: 600
  playerNameUntil: 0
  stopTrackingAt: 0
  disableInWorlds:
    - Lobby

trackerLocation:
  enable: true
  maxDistance: 0
  locations:
  disableInWorlds: 
  - Lobby