name: CompassRadar
author: xX_andrescol_Xx
main: co.andrescol.mc.plugin.compassradar.CompassRadarPlugin
version: 1.1.0
description: You can tracker players and locations with this plugin
api-version: 1.19

commands:
  compassradar:
    description: plugin command
    aliases: compass
    permission: compassradar.cmd
permissions:
  compassradar.cmd: { default: op, description: allow to see the help message }
  compassradar.use: { default: op, description: allow use the compass as radar from main hand }
  compassradar.cmd.player: { default: op, description: allow use the command /compass player }
  compassradar.cmd.location: { default: op, description: allow use the command /compass location }
  compassradar.cmd.addlocation: { default: op, description: allow to add a location }
  compassradar.cmd.removelocation: { default: op, description: allow to remove a location }
  compassradar.cmd.listlocation: { default: op, description: allow to show the location list }
  compassradar.cmd.reload: { default: op, description: allow to reload the plugin }
  compassradar.player:
    default: op
    description: allow to use thre radar and help command
    children:
      compassradar.cmd: true
      compassradar.cmd.player: true
      compassradar.cmd.location: true
      compassradar.use: true